In [1]:
import numpy as np
import pandas as pd
from linearmodels import PanelOLS
from linearmodels import RandomEffects

In [2]:
from linearmodels.datasets import jobtraining
data = jobtraining.load()
data

,year,fcode,employ,sales,avgsal,scrap,rework,tothrs,union,grant,...,grant_1,clscrap,cgrant,clemploy,clsales,lavgsal,clavgsal,cgrant_1,chrsemp,clhrsemp
0,1987,410032,100.0,47000000.0,35000.0,NaN,NaN,12.0,0,0,...,0,NaN,0,NaN,NaN,10.463100,NaN,NaN,NaN,NaN
1,1988,410032,131.0,43000000.0,37000.0,NaN,NaN,8.0,0,0,...,0,NaN,0,0.270027,-0.088949,10.518670,0.055570,0.0,-8.946565,-1.165385
2,1989,410032,123.0,49000000.0,39000.0,NaN,NaN,8.0,0,0,...,0,NaN,0,-0.063013,0.130621,10.571320,0.052644,0.0,0.198597,0.047832
3,1987,410440,12.0,1560000.0,10500.0,NaN,NaN,12.0,0,0,...,0,NaN,0,NaN,NaN,9.259130,NaN,NaN,NaN,NaN
4,1988,410440,13.0,1970000.0,11000.0,NaN,NaN,12.0,0,0,...,0,NaN,0,0.080043,0.233347,9.305651,0.046520,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,1988,419483,108.0,11500000.0,14810.0,25.0,NaN,0.0,1,0,...,0,0.223144,0,-0.208218,0.044453,9.603058,0.059321,0.0,0.000000,0.000000
467,1989,419483,129.0,12000000.0,14227.0,30.0,NaN,20.0,1,0,...,0,0.182321,0,0.177681,0.042559,9.562897,-0.040161,0.0,3.100775,1.411176
468,1987,419486,80.0,7000000.0,16000.0,NaN,NaN,0.0,0,0,...,0,NaN,0,NaN,NaN,9.680344,NaN,NaN,NaN,NaN
469,1988,419486,90.0,8500000.0,17000.0,NaN,NaN,0.0,0,0,...,0,NaN,0,0.117783,0.194157,9.740969,0.060625,0.0,0.000000,0.000000
470,1989,419486,100.0,9900000.0,18000.0,NaN,NaN,40.0,0,1,...,0,NaN,1,0.105360,0.152469,9.798127,0.057159,0.0,36.000000,3.610918

In [3]:
year = pd.Categorical(data.year)
data = data.set_index(['fcode','year'])
data['year'] = year

In [4]:
data

             employ       sales   avgsal  scrap  rework  tothrs  union  grant  \
fcode  year
410032 1987   100.0  47000000.0  35000.0    NaN     NaN    12.0      0      0
       1988   131.0  43000000.0  37000.0    NaN     NaN     8.0      0      0
       1989   123.0  49000000.0  39000.0    NaN     NaN     8.0      0      0
410440 1987    12.0   1560000.0  10500.0    NaN     NaN    12.0      0      0
       1988    13.0   1970000.0  11000.0    NaN     NaN    12.0      0      0
...             ...         ...      ...    ...     ...     ...    ...    ...
419483 1988   108.0  11500000.0  14810.0   25.0     NaN     0.0      1      0
       1989   129.0  12000000.0  14227.0   30.0     NaN    20.0      1      0
419486 1987    80.0   7000000.0  16000.0    NaN     NaN     0.0      0      0
       1988    90.0   8500000.0  17000.0    NaN     NaN     0.0      0      0
       1989   100.0   9900000.0  18000.0    NaN     NaN    40.0      0      1

             d89  d88  ...   clscrap  cgrant  clemploy   clsales    lavgsal  \
fcode  year            ...
410032 1987    0    0  ...       NaN       0       NaN       NaN  10.463100
       1988    0    1  ...       NaN       0  0.270027 -0.088949  10.518670
       1989    1    0  ...       NaN       0 -0.063013  0.130621  10.571320
410440 1987    0    0  ...       NaN       0       NaN       NaN   9.259130
       1988    0    1  ...       NaN       0  0.080043  0.233347   9.305651
...          ...  ...  ...       ...     ...       ...       ...        ...
419483 1988    0    1  ...  0.223144       0 -0.208218  0.044453   9.603058
       1989    1    0  ...  0.182321       0  0.177681  0.042559   9.562897
419486 1987    0    0  ...       NaN       0       NaN       NaN   9.680344
       1988    0    1  ...       NaN       0  0.117783  0.194157   9.740969
       1989    1    0  ...       NaN       1  0.105360  0.152469   9.798127

             clavgsal  cgrant_1    chrsemp  clhrsemp  year
fcode  year
410032 1987       NaN       NaN        NaN       NaN  1987
       1988  0.055570       0.0  -8.946565 -1.165385  1988
       1989  0.052644       0.0   0.198597  0.047832  1989
410440 1987       NaN       NaN        NaN       NaN  1987
       1988  0.046520       0.0   0.000000  0.000000  1988
...               ...       ...        ...       ...   ...
419483 1988  0.059321       0.0   0.000000  0.000000  1988
       1989 -0.040161       0.0   3.100775  1.411176  1989
419486 1987       NaN       NaN        NaN       NaN  1987
       1988  0.060625       0.0   0.000000  0.000000  1988
       1989  0.057159       0.0  36.000000  3.610918  1989

[471 rows x 29 columns]

In [5]:
%conda install -c conda-forge statsmodels

Collecting package metadata (current_repodata.json): \ ^C
failed

Note: you may need to restart the kernel to use updated packages.

In [9]:
import statsmodels.api as sm
exog_vars = ['grant','employ']
exog = sm.add_constant(data[exog_vars])
mod = RandomEffects(data.clscrap, exog)
re_res = mod.fit()
print(re_res)

/home/richa/anaconda3/lib/python3.7/site-packages/linearmodels/utility.py:549: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                clscrap   R-squared:                        0.0165
Estimator:              RandomEffects   R-squared (Between):              0.0314
No. Observations:                 105   R-squared (Within):               0.0015
Date:                Tue, Jul 21 2020   R-squared (Overall):              0.0199
Time:                        15:48:28   Log-likelihood                   -77.721
Cov. Estimator:            Unadjusted
                                        F-statistic:                      0.8542
Entities:                          53   P-value                           0.4286
Avg Obs:                       1.9811   Distribution:                   F(2,102)
Min Obs:                       1.0000
Max Obs:                       2.0000   F-statistic (robust):             0.8634
                                        P-value                           0.4248
Time periods:                       2   Distribution:                   F(2,102)
Avg Obs:                       52.500
Min Obs:                       52.000
Max Obs:                       53.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const         -0.1670     0.0892    -1.8721     0.0641     -0.3440      0.0099
grant         -0.1471     0.1214    -1.2115     0.2285     -0.3879      0.0937
employ        -0.0003     0.0008    -0.3893     0.6979     -0.0019      0.0013
==============================================================================

In [10]:
mod = PanelOLS(data.clscrap, exog)
re_res = mod.fit()
print(re_res)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                clscrap   R-squared:                        0.0205
Estimator:                   PanelOLS   R-squared (Between):              0.0362
No. Observations:                 105   R-squared (Within):              -0.0048
Date:                Tue, Jul 21 2020   R-squared (Overall):              0.0205
Time:                        15:49:08   Log-likelihood                   -91.226
Cov. Estimator:            Unadjusted
                                        F-statistic:                      1.0653
Entities:                          53   P-value                           0.3484
Avg Obs:                       1.9811   Distribution:                   F(2,102)
Min Obs:                       1.0000
Max Obs:                       2.0000   F-statistic (robust):             1.0653
                                        P-value                           0.3484
Time periods:                       2   Distribution:                   F(2,102)
Avg Obs:                       52.500
Min Obs:                       52.000
Max Obs:                       53.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const         -0.1622     0.0830    -1.9546     0.0534     -0.3267      0.0024
grant         -0.1783     0.1297    -1.3752     0.1721     -0.4356      0.0789
employ        -0.0003     0.0007    -0.3640     0.7166     -0.0017      0.0012
==============================================================================

In [15]:
import statsmodels.formula.api as smf
data = jobtraining.load()
data['year'] = pd.Categorical(data.year)
FE_ols = smf.ols(formula='clscrap ~ 1 + grant + employ + C(fcode)', data = data).fit()
print(FE_ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                clscrap   R-squared:                       0.630
Model:                            OLS   Adj. R-squared:                  0.230
Method:                 Least Squares   F-statistic:                     1.577
Date:                Tue, 21 Jul 2020   Prob (F-statistic):             0.0529
Time:                        15:51:35   Log-Likelihood:                -40.109
No. Observations:                 105   AIC:                             190.2
Df Residuals:                      50   BIC:                             336.2
Df Model:                          54
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -0.0558      0.233     -0.239      0.812      -0.524       0.412
C(fcode)[T.410440]  1.777e-15   4.45e-14      0.040      0.968   -8.75e-14    9.11e-14
C(fcode)[T.410495] -1.509e-13   1.35e-13     -1.121      0.268   -4.21e-13    1.19e-13
C(fcode)[T.410500] -5.458e-14   5.75e-14     -0.950      0.347    -1.7e-13    6.08e-14
C(fcode)[T.410501] -1.212e-13   1.73e-13     -0.701      0.486   -4.68e-13    2.26e-13
C(fcode)[T.410509] -3.023e-14   8.66e-14     -0.349      0.728   -2.04e-13    1.44e-13
C(fcode)[T.410513]  -8.68e-14   1.43e-13     -0.607      0.546   -3.74e-13       2e-13
C(fcode)[T.410517]  1.123e-14   5.26e-14      0.214      0.832   -9.43e-14    1.17e-13
C(fcode)[T.410518] -3.605e-14   4.54e-14     -0.794      0.431   -1.27e-13    5.52e-14
C(fcode)[T.410521]  2.109e-14   1.19e-13      0.177      0.860   -2.18e-13     2.6e-13
C(fcode)[T.410523]     0.1627      0.369      0.440      0.662      -0.579       0.905
C(fcode)[T.410529]  2.035e-15   9.69e-15      0.210      0.834   -1.74e-14    2.15e-14
C(fcode)[T.410531]  2.251e-14   9.64e-14      0.234      0.816   -1.71e-13    2.16e-13
C(fcode)[T.410533] -4.559e-14   1.13e-13     -0.404      0.688   -2.72e-13    1.81e-13
C(fcode)[T.410535] -5.643e-14   9.17e-14     -0.615      0.541   -2.41e-13    1.28e-13
C(fcode)[T.410536]  3.189e-14   4.55e-14      0.700      0.487   -5.96e-14    1.23e-13
C(fcode)[T.410538]     0.1099      0.509      0.216      0.830      -0.912       1.131
C(fcode)[T.410540]  1.444e-15   8.31e-14      0.017      0.986   -1.65e-13    1.68e-13
C(fcode)[T.410544]  1.904e-14   3.69e-14      0.516      0.608   -5.51e-14    9.32e-14
C(fcode)[T.410546] -2.729e-14   3.19e-14     -0.856      0.396   -9.14e-14    3.68e-14
C(fcode)[T.410547]  -1.65e-14   1.65e-13     -0.100      0.921   -3.49e-13    3.16e-13
C(fcode)[T.410556]  5.906e-14   1.06e-13      0.558      0.579   -1.53e-13    2.72e-13
C(fcode)[T.410560] -7.233e-14   1.04e-13     -0.698      0.489   -2.81e-13    1.36e-13
C(fcode)[T.410561]  1.037e-14    1.1e-14      0.943      0.350   -1.17e-14    3.25e-14
C(fcode)[T.410562]  3.211e-15    1.8e-14      0.178      0.859   -3.29e-14    3.94e-14
C(fcode)[T.410563]     0.1335      0.363      0.368      0.715      -0.596       0.863
C(fcode)[T.410564]  2.121e-14   7.11e-14      0.298      0.767   -1.22e-13    1.64e-13
C(fcode)[T.410565]    -1.6648      0.399     -4.172      0.000      -2.466      -0.863
C(fcode)[T.410566]    -0.1337      0.403     -0.332      0.741      -0.943       0.675
C(fcode)[T.410567]    -0.4746      0.367     -1.292      0.202      -1.212       0.263
C(fcode)[T.410569] -6.941e-14   9.86e-14     -0.704      0.485   -2.67e-13    1.29e-13
C(fcode)[T.410571]  5.942e-15   5.99e-15      0.992      0.326   -6.09e-15     1.8e-14
C(fcode)[T.410577]     0.2321      0.367      0.633      0.530      -0.504       0.969
C(fcode)[T.410586] -3.651e-15   1.75e-15     -2.084      0.042   -7.17e-15   -1.32e-16
C(fcode)[T.410591] -1.007e-14   1.06e-14     -0.954      0.345   -3.13e-14    1.11e-14
C(fcode)[T.410592]    -0.1145      0.402     -0.285      0.777      -0.922       0.693
C(fcode)[T.410593]     0.0666      0.417      0.160      0.874      -0.772       0.905
C(fcode)[T.410596]    -0.3634      0.398     -0.913      0.365      -1.163       0.436
C(fcode)[T.410603] -1.722e-14   7.45e-15     -2.311      0.025   -3.22e-14   -2.25e-15
C(fcode)[T.410604] -6.029e-15   8.57e-15     -0.704      0.485   -2.32e-14    1.12e-14
C(fcode)[T.410606]     0.0688      0.410      0.168      0.868      -0.755       0.892
C(fcode)[T.410609] -1.132e-15   4.59e-16     -2.465      0.017   -2.06e-15    -2.1e-16
C(fcode)[T.410612]  1.402e-14   6.37e-15      2.201      0.032    1.23e-15    2.68e-14
C(fcode)[T.410626]     0.0170      0.384      0.044      0.965      -0.755       0.789
C(fcode)[T.410627]  -2.42e-15   2.65e-15     -0.912      0.366   -7.75e-15    2.91e-15
C(fcode)[T.410629]    -0.3466      0.394     -0.880      0.383      -1.138       0.445
C(fcode)[T.410635] -1.957e-14   7.14e-15     -2.742      0.008   -3.39e-14   -5.24e-15
C(fcode)[T.410636]  3.796e-15   2.33e-15      1.631      0.109    -8.8e-16    8.47e-15
C(fcode)[T.410639] -2.439e-14   9.51e-15     -2.565      0.013   -4.35e-14   -5.29e-15
C(fcode)[T.410640]  1.342e-14   5.12e-15      2.621      0.012    3.14e-15    2.37e-14
C(fcode)[T.410641] -7.889e-15   6.26e-15     -1.261      0.213   -2.05e-14    4.68e-15
C(fcode)[T.410642]  1.186e-15   6.13e-16      1.933      0.059   -4.62e-17    2.42e-15
C(fcode)[T.410649]  8.753e-15   5.09e-15      1.719      0.092   -1.48e-15     1.9e-14
C(fcode)[T.410653]     0.1192      0.406      0.294      0.770      -0.696       0.934
C(fcode)[T.410665]    -0.1715      0.405     -0.423      0.674      -0.985       0.642
C(fcode)[T.410679]  2.638e-15   3.26e-15      0.809      0.423   -3.91e-15    9.19e-15
C(fcode)[T.410680]  2.125e-14   8.97e-15      2.370      0.022    3.24e-15    3.93e-14
C(fcode)[T.410685]     0.3473      0.395      0.879      0.384      -0.446       1.141
C(fcode)[T.410686] -2.176e-14   7.97e-15     -2.730      0.009   -3.78e-14   -5.75e-15
C(fcode)[T.418006] -3.302e-15   1.49e-15     -2.213      0.032    -6.3e-15   -3.04e-16
C(fcode)[T.418007]  7.121e-15   4.83e-15      1.474      0.147   -2.58e-15    1.68e-14
C(fcode)[T.418008] -7.687e-15   3.35e-15     -2.298      0.026   -1.44e-14   -9.68e-16
C(fcode)[T.418011]    -0.6386      0.379     -1.686      0.098      -1.399       0.122
C(fcode)[T.418013] -9.221e-15   4.75e-15     -1.943      0.058   -1.88e-14    3.11e-16
C(fcode)[T.418014] -1.657e-15   1.62e-15     -1.024      0.311   -4.91e-15    1.59e-15
C(fcode)[T.418021]     0.1077      0.414      0.260      0.796      -0.724       0.939
C(fcode)[T.418024]  5.004e-15    3.7e-15      1.351      0.183   -2.44e-15    1.24e-14
C(fcode)[T.418035]    -0.2010      0.389     -0.517      0.608      -0.983       0.581
C(fcode)[T.418036] -2.908e-16   3.17e-16     -0.919      0.363   -9.27e-16    3.45e-16
C(fcode)[T.418045]     0.0883      0.402      0.220      0.827      -0.719       0.896
C(fcode)[T.418046]  1.178e-15    1.3e-15      0.906      0.369   -1.43e-15    3.79e-15
C(fcode)[T.418051] -3.304e-15   2.83e-15     -1.167      0.249   -8.99e-15    2.38e-15
C(fcode)[T.418052] -1.417e-15   2.29e-15     -0.619      0.539   -6.01e-15    3.18e-15
C(fcode)[T.418054]     0.0785      0.364      0.215      0.830      -0.653       0.810
C(fcode)[T.418065]     0.6541      0.901      0.726      0.471      -1.155       2.463
C(fcode)[T.418066]   -1.6e-15   1.18e-15     -1.356      0.181   -3.97e-15     7.7e-16
C(fcode)[T.418076]    -0.5551      0.362     -1.535      0.131      -1.282       0.171
C(fcode)[T.418083]    -0.2750      0.365     -0.753      0.455      -1.008       0.458
C(fcode)[T.418084]  9.353e-16   9.16e-16      1.021      0.312   -9.05e-16    2.78e-15
C(fcode)[T.418091]    -0.8553      0.518     -1.652      0.105      -1.895       0.185
C(fcode)[T.418097]     0.2907      0.412      0.705      0.484      -0.538       1.119
C(fcode)[T.418098]  3.045e-15   2.13e-15      1.427      0.160   -1.24e-15    7.33e-15
C(fcode)[T.418107]    -0.2458      0.390     -0.630      0.532      -1.030       0.538
C(fcode)[T.418109]  1.861e-15   1.97e-15      0.947      0.348   -2.09e-15    5.81e-15
C(fcode)[T.418118]    -1.0371      0.409     -2.535      0.014      -1.859      -0.215
C(fcode)[T.418124] -1.078e-15    7.9e-16     -1.364      0.179   -2.67e-15    5.09e-16
C(fcode)[T.418125]     0.5437      0.434      1.251      0.217      -0.329       1.416
C(fcode)[T.418126] -1.578e-15   1.55e-15     -1.017      0.314   -4.69e-15    1.54e-15
C(fcode)[T.418140]    -0.4555      0.401     -1.136      0.261      -1.261       0.350
C(fcode)[T.418147] -2.806e-16    2.3e-16     -1.221      0.228   -7.42e-16    1.81e-16
C(fcode)[T.418163]     0.0662      0.362      0.183      0.856      -0.661       0.793
C(fcode)[T.418168]     1.5699      0.413      3.797      0.000       0.739       2.400
C(fcode)[T.418177]     0.3393      0.391      0.868      0.390      -0.446       1.125
C(fcode)[T.418183]  2.607e-16   1.89e-16      1.378      0.174   -1.19e-16    6.41e-16
C(fcode)[T.418185] -7.806e-15   5.39e-15     -1.448      0.154   -1.86e-14    3.02e-15
C(fcode)[T.418213]  1.176e-19   8.75e-20      1.345      0.185    -5.8e-20    2.93e-19
C(fcode)[T.418220]  2.641e-15   1.92e-15      1.376      0.175   -1.21e-15     6.5e-15
C(fcode)[T.418225] -9.438e-18   7.21e-18     -1.308      0.197   -2.39e-17    5.05e-18
C(fcode)[T.418229]  3.745e-15   2.53e-15      1.479      0.146   -1.34e-15    8.83e-15
C(fcode)[T.418237]    -0.0527      0.392     -0.135      0.894      -0.839       0.734
C(fcode)[T.418239]  3.809e-19   4.41e-18      0.086      0.931   -8.47e-18    9.23e-18
C(fcode)[T.418243]   1.87e-17   8.43e-18      2.219      0.031    1.78e-18    3.56e-17
C(fcode)[T.418245]  5.875e-18   7.13e-17      0.082      0.935   -1.37e-16    1.49e-16
C(fcode)[T.419198]    -0.1765      0.417     -0.423      0.674      -1.014       0.661
C(fcode)[T.419201]     0.0883      0.402      0.220      0.827      -0.719       0.896
C(fcode)[T.419242]     0.3632      0.372      0.976      0.334      -0.384       1.111
C(fcode)[T.419268]    -0.1248      0.425     -0.293      0.770      -0.979       0.730
C(fcode)[T.419272]     0.0757      0.377      0.201      0.842      -0.682       0.833
C(fcode)[T.419275]          0          0        nan        nan           0           0
C(fcode)[T.419276]          0          0        nan        nan           0           0
C(fcode)[T.419289]    -0.1175      0.411     -0.286      0.776      -0.944       0.709
C(fcode)[T.419297]     0.5836      0.501      1.164      0.250      -0.424       1.591
C(fcode)[T.419298]          0          0        nan        nan           0           0
C(fcode)[T.419302]          0          0        nan        nan           0           0
C(fcode)[T.419303]          0          0        nan        nan           0           0
C(fcode)[T.419305]          0          0        nan        nan           0           0
C(fcode)[T.419307]     0.6339      0.774      0.819      0.416      -0.920       2.188
C(fcode)[T.419309]          0          0        nan        nan           0           0
C(fcode)[T.419312]          0          0        nan        nan           0           0
C(fcode)[T.419319]          0          0        nan        nan           0           0
C(fcode)[T.419328]          0          0        nan        nan           0           0
C(fcode)[T.419335]          0          0        nan        nan           0           0
C(fcode)[T.419339]     0.1113      0.367      0.304      0.763      -0.625       0.848
C(fcode)[T.419343]     0.2733      0.567      0.482      0.632      -0.865       1.411
C(fcode)[T.419344]          0          0        nan        nan           0           0
C(fcode)[T.419347]          0          0        nan        nan           0           0
C(fcode)[T.419351]          0          0        nan        nan           0           0
C(fcode)[T.419357]    -0.4621      0.362     -1.277      0.207      -1.189       0.264
C(fcode)[T.419375]          0          0        nan        nan           0           0
C(fcode)[T.419376]          0          0        nan        nan           0           0
C(fcode)[T.419378]    -0.2088      0.390     -0.535      0.595      -0.993       0.575
C(fcode)[T.419379]          0          0        nan        nan           0           0
C(fcode)[T.419380]          0          0        nan        nan           0           0
C(fcode)[T.419381]    -0.1640      0.416     -0.394      0.695      -1.000       0.672
C(fcode)[T.419384]          0          0        nan        nan           0           0
C(fcode)[T.419388]    -0.1489      0.384     -0.387      0.700      -0.921       0.623
C(fcode)[T.419392]          0          0        nan        nan           0           0
C(fcode)[T.419400]          0          0        nan        nan           0           0
C(fcode)[T.419401]          0          0        nan        nan           0           0
C(fcode)[T.419406]          0          0        nan        nan           0           0
C(fcode)[T.419409]     0.1797      0.361      0.497      0.621      -0.546       0.906
C(fcode)[T.419410]          0          0        nan        nan           0           0
C(fcode)[T.419420]          0          0        nan        nan           0           0
C(fcode)[T.419432]     0.7681      0.900      0.853      0.398      -1.040       2.577
C(fcode)[T.419433]          0          0        nan        nan           0           0
C(fcode)[T.419434]          0          0        nan        nan           0           0
C(fcode)[T.419449]          0          0        nan        nan           0           0
C(fcode)[T.419450]          0          0        nan        nan           0           0
C(fcode)[T.419459]     0.2349      0.503      0.467      0.642      -0.775       1.244
C(fcode)[T.419461]          0          0        nan        nan           0           0
C(fcode)[T.419467]          0          0        nan        nan           0           0
C(fcode)[T.419472]          0          0        nan        nan           0           0
C(fcode)[T.419473]          0          0        nan        nan           0           0
C(fcode)[T.419479]          0          0        nan        nan           0           0
C(fcode)[T.419482]     0.1097      0.400      0.274      0.785      -0.694       0.913
C(fcode)[T.419483]     0.5150      0.397      1.297      0.200      -0.282       1.312
C(fcode)[T.419486]          0          0        nan        nan           0           0
grant                 -0.0475      0.143     -0.333      0.741      -0.334       0.239
employ                -0.0022      0.003     -0.660      0.512      -0.009       0.004
==============================================================================
Omnibus:                       17.255   Durbin-Watson:                   3.049
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               82.359
Skew:                          -0.000   Prob(JB):                     1.31e-18
Kurtosis:                       7.339   Cond. No.                     2.61e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
[3] The smallest eigenvalue is 1.81e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

/home/richa/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:1362: RuntimeWarning: invalid value encountered in true_divide
  return self.params / self.bse
/home/richa/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/home/richa/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/home/richa/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)